#!/usr/bin/env python3
"""Reference implementation and fixtures for the Firestore pairing-membership proof.

Standard library only; independent of CloudPairingAuth.kt / CloudPairingAuth.swift, which
both load firestore-pairing-v1-test-vectors.properties.

  membershipKey = HKDF-SHA256(IKM = 32-byte pairing key, salt = empty,
                              info = "ClipSync/Firestore/Pairing/v1", L = 32)

  message = len16(pairingId) || pairingId || len16(androidUid) || androidUid
            || len16(macUid) || macUid || len16(nonce) || nonce
            (len16 = 2-byte big-endian length; strings UTF-8; nonce = 16 raw bytes)

  proof   = lowercase hex( HMAC-SHA256(membershipKey, message) )

The phone (which scanned the Mac's QR code, and so holds the pairing key and the Mac's
Firebase UID) writes the proof into the pending pairing document. The Mac verifies it
locally before adding its own UID to `members`. Firestore and Cloud Functions never see
the pairing key.
"""

import hashlib
import hmac
import os
import struct

INFO = b"ClipSync/Firestore/Pairing/v1"


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt if salt else b"\x00" * 32, ikm, hashlib.sha256).digest()
    okm, block, counter = b"", b"", 1
    while len(okm) < length:
        block = hmac.new(prk, block + info + bytes([counter]), hashlib.sha256).digest()
        okm += block
        counter += 1
    return okm[:length]


def field(b: bytes) -> bytes:
    return struct.pack(">H", len(b)) + b


def main() -> None:
    root = bytes(range(32))
    key = hkdf_sha256(root, b"", INFO, 32)
    assert key != hkdf_sha256(root, b"", b"ClipSync/TCP/Auth/v1", 32)
    assert key != hkdf_sha256(root, b"", b"ClipSync/BLE/Auth/v1", 32)

    pairing_id = "Xq3Lz9PairingDoc0001"
    android_uid = "aNdRoIdUiD0123456789abcdEF12"
    mac_uid = "mAcUiD9876543210zyxwvutsRQ34"
    nonce = bytes(range(0xA0, 0xB0))
    message = (field(pairing_id.encode()) + field(android_uid.encode())
               + field(mac_uid.encode()) + field(nonce))
    proof = hmac.new(key, message, hashlib.sha256).hexdigest()

    out = {
        "rootKey": root.hex(),
        "membershipKey": key.hex(),
        "pairingId": pairing_id,
        "androidUid": android_uid,
        "macUid": mac_uid,
        "nonce": nonce.hex(),
        "message": message.hex(),
        "proof": proof,
    }
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "firestore-pairing-v1-test-vectors.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# ClipSync Firestore pairing-membership proof v1 test vectors.\n")
        f.write("# Generated by generate_firestore_pairing_vectors.py. pairingId/androidUid/macUid\n")
        f.write("# are plain strings; everything else is hex.\n")
        for k, v in out.items():
            f.write(f"{k}={v}\n")
    print(open(path, encoding="utf-8").read())


if __name__ == "__main__":
    main()
