#!/usr/bin/env python3
"""Reference implementation and fixture generator for ClipSync BLE control protocol v2.

Standard library only; independent of BleControlProtocol.kt and BleControlProtocol.swift,
which both load the fixtures written to ble-v2-test-vectors.properties.

Envelope (big-endian):
    off len field
      0   4  magic "CLB2"
      4   1  version = 0x02
      5   1  message type   (0x10-0x18 Android->Mac, 0x20-0x26 Mac->Android)
      6   1  direction      (0x01 Android->Mac, 0x02 Mac->Android)
      7   1  reserved = 0x00
      8   8  timestampMs    int64
     16  16  messageId
     32   2  payloadLen     uint16
     34   N  payload        TLV: [tag(1)][len(2)][value], tags strictly ascending
   34+N  32  HMAC-SHA256(bleAuthKey, bytes[0 : 34+N])

    bleAuthKey = HKDF-SHA256(IKM = 32-byte pairing key, salt = empty,
                             info = "ClipSync/BLE/Auth/v1", L = 32)
"""

import hashlib
import hmac
import os
import struct

INFO = b"ClipSync/BLE/Auth/v1"


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt if salt else b"\x00" * 32, ikm, hashlib.sha256).digest()
    okm, block, counter = b"", b"", 1
    while len(okm) < length:
        block = hmac.new(prk, block + info + bytes([counter]), hashlib.sha256).digest()
        okm += block
        counter += 1
    return okm[:length]


def tlv(fields: dict) -> bytes:
    return b"".join(bytes([tag]) + struct.pack(">H", len(v)) + v for tag, v in sorted(fields.items()))


def envelope(key: bytes, type_: int, direction: int, ts: int, msg_id: bytes, fields: dict) -> bytes:
    payload = tlv(fields)
    signed = (b"CLB2" + bytes([0x02, type_, direction, 0x00]) + struct.pack(">q", ts)
              + msg_id + struct.pack(">H", len(payload)) + payload)
    return signed + hmac.new(key, signed, hashlib.sha256).digest()


def main() -> None:
    root = bytes(range(32))
    auth = hkdf_sha256(root, b"", INFO, 32)
    tcp_auth = hkdf_sha256(root, b"", b"ClipSync/TCP/Auth/v1", 32)
    assert auth != tcp_auth

    ts = 1_700_000_000_000
    msg_id = bytes(range(0xB0, 0xC0))
    request_id = bytes(range(0xC0, 0xD0))
    # ping_ack (Android -> Mac) answering request C0..CF, with IP, port and device name.
    ping_ack = envelope(auth, 0x12, 0x01, ts, msg_id, {
        0x01: b"192.168.1.42",
        0x02: struct.pack(">H", 8766),
        0x07: "Pixel 8 é".encode("utf-8"),
        0x08: request_id,
    })
    # setting (Mac -> Android): ultra_fast = true.
    setting = envelope(auth, 0x23, 0x02, ts, msg_id, {0x0B: b"\x01"})

    out = {
        "rootKey": root.hex(),
        "bleAuthKey": auth.hex(),
        "timestampMs": str(ts),
        "messageId": msg_id.hex(),
        "requestId": request_id.hex(),
        "pingAckEnvelope": ping_ack.hex(),
        "pingAckMac": ping_ack[-32:].hex(),
        "settingEnvelope": setting.hex(),
    }
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ble-v2-test-vectors.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# ClipSync BLE control protocol v2 shared test vectors (hex unless noted).\n")
        f.write("# Generated by generate_ble_v2_vectors.py.\n")
        f.write("# pingAckEnvelope: type ping_ack, Android->Mac, ip=192.168.1.42, port=8766,\n")
        f.write("#   deviceName=\"Pixel 8 é\", replyTo=requestId. settingEnvelope: ultra_fast=1.\n")
        for k, v in out.items():
            f.write(f"{k}={v}\n")
    print(open(path, encoding="utf-8").read())


if __name__ == "__main__":
    main()
