#!/usr/bin/env python3
"""Reference implementation and fixture generator for ClipSync TCP protocol v2.

Uses only the Python standard library, so it is independent of both app implementations
(Kotlin: TcpFrameProtocol.kt, Swift: TcpFrameProtocol.swift). It writes the shared
fixtures in tcp-v2-test-vectors.properties, which the Android unit tests and the Mac
policy tests both load.

AES-GCM is not in the standard library, so the chunk ciphertext fixture is produced by
CryptoKit (mac/PolicyTests) and verified by both test suites; everything else here is
computed independently.

Protocol v2 (all integers big-endian, strings UTF-8):

  Header
    off len field
      0   4  magic "CLS2" (0x43 0x4C 0x53 0x32)
      4   1  version = 0x02
      5   1  type: 0x01 text, 0x02 image, 0x03 file
      6   1  direction: 0x01 Android->Mac, 0x02 Mac->Android
      7   1  reserved = 0x00
      8   8  totalSize   int64   plaintext/application bytes (> 0)
     16   4  chunkSize   uint32  plaintext bytes per chunk (1024 .. 4 MiB)
     20   8  timestampMs int64   sender clock, Unix epoch milliseconds
     28  16  sessionId   random bytes, unique per transfer
     44   2  nameLen     uint16  (0 .. 1024)
     46   N  name        UTF-8
   46+N  32  HMAC-SHA256(authKey, bytes[0 : 46+N])

  authKey = HKDF-SHA256(IKM = 32-byte pairing key, salt = empty,
                        info = "ClipSync/TCP/Auth/v1", L = 32)

  Chunk i (i = 0, 1, ...; never sent on the wire, both sides count)
    [4-byte sealedLen][12-byte nonce][ciphertext][16-byte tag]
    sealedLen = plainLen(i) + 28, plainLen(i) = min(chunkSize, totalSize - i*chunkSize)
    AES-256-GCM with the pairing key itself and
    AAD (31 bytes) = version(1) || sessionId(16) || type(1) || direction(1)
                     || totalSize(8) || chunkIndex(4, uint32)
"""

import hashlib
import hmac
import os
import struct

INFO = b"ClipSync/TCP/Auth/v1"


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt if salt else b"\x00" * 32, ikm, hashlib.sha256).digest()
    okm, block, counter = b"", b"", 1
    while len(okm) < length:
        block = hmac.new(prk, block + info + bytes([counter]), hashlib.sha256).digest()
        okm += block
        counter += 1
    return okm[:length]


def header_prefix(type_, direction, total, chunk, ts, session, name: bytes) -> bytes:
    return (b"CLS2" + bytes([0x02, type_, direction, 0x00])
            + struct.pack(">qIq", total, chunk, ts) + session
            + struct.pack(">H", len(name)) + name)


def aad(session, type_, direction, total, index) -> bytes:
    return bytes([0x02]) + session + bytes([type_, direction]) + struct.pack(">qI", total, index)


def main() -> None:
    # RFC 5869 test case 1 sanity check of the HKDF construction.
    rfc = hkdf_sha256(bytes([0x0b] * 22), bytes(range(13)), bytes(range(0xf0, 0xfa)), 42)
    assert rfc.hex() == ("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf"
                         "34007208d5b887185865"), rfc.hex()

    root = bytes(range(32))
    auth = hkdf_sha256(root, b"", INFO, 32)
    session = bytes(range(0xA0, 0xB0))
    name = "photo é.jpg".encode("utf-8")
    prefix = header_prefix(0x03, 0x01, 5_000_001, 1_048_576, 1_700_000_000_000, session, name)
    mac = hmac.new(auth, prefix, hashlib.sha256).digest()
    chunk_aad = aad(session, 0x03, 0x01, 5_000_001, 3)

    out = {
        "rootKey": root.hex(),
        "authKey": auth.hex(),
        "sessionId": session.hex(),
        "fileName": name.hex(),
        "headerPrefix": prefix.hex(),
        "headerMac": mac.hex(),
        "header": (prefix + mac).hex(),
        "aadChunk3": chunk_aad.hex(),
    }
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tcp-v2-test-vectors.properties")
    existing = {}
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
    # Keep the CryptoKit-produced GCM fixture, which this script cannot compute.
    for k in ("gcmNonce", "gcmPlaintext", "gcmSealedChunk0"):
        if k in existing:
            out[k] = existing[k]

    with open(path, "w", encoding="utf-8") as f:
        f.write("# ClipSync TCP protocol v2 shared test vectors (hex).\n")
        f.write("# Generated by generate_tcp_v2_vectors.py; gcm* entries come from CryptoKit\n")
        f.write("# (mac/PolicyTests) and are verified by both platforms.\n")
        f.write("# Header: type=file, direction=Android->Mac, totalSize=5000001,\n")
        f.write("#         chunkSize=1048576, timestampMs=1700000000000, name=\"photo é.jpg\".\n")
        for k, v in out.items():
            f.write(f"{k}={v}\n")
    print(open(path, encoding="utf-8").read())


if __name__ == "__main__":
    main()
